project:
  type: book

format: 
  html:
    theme:
      light: flatly
      dark: darkly

book:
# the next option enbale the reader-mode. It hides to TOC and the otpion seems the be automatically enabled by default on Chromium
  #reader-mode: true
  repo-url: https://github.com/fennicahub/fennica
  repo-actions: issue
  sidebar:
    border: true
    title: Harmonized Finnish National Bibliography
    tools:
      - icon: twitter
        href: https://twitter.com/intent/tweet?text=Harmonized%20Finnish%20National%20Bibliography
      - icon: facebook
        href: https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Ffennica-fennica.rahtiapp.fi%2Findex.html

  # file with '#' are not used anymore
  # files with '##' are the one that need to be corrected 
  chapters:
  - index.qmd
  - author_name.qmd
  - author_date.qmd
  #- language.qmd
  #- publisher.qmd
  #- publication_interval.qmd
  #- publication_place.qmd
  #- publication_time.qmd
  #- physical_dimensions.qmd
  #- title.qmd
  #- title_uniform.qmd
  #- publication_frequency.qmd
  
  #physical_extent.qmd
  
  #- subject_geography-qmd
  #- subject_topic.qmd
  #- successor.qmd
  #- holder.qmd
  #- note_dissertation.qmd
  #- note_granter.qmd
  #- note_source.qmd
  #- corporate.qmd
  #- uncontrolled.qmd
  appendices :
    - acknowledgments.qmd
    - technical_information.qmd

