project:
  type: book
  output-dir: _book_quarto
format: html
book:
  chapters:
    - index.qmd
    - author_date.qmd
    - author_name.qmd
    - corporate.qmd
    - language.qmd
    - holder.qmd
    - note_dissertation.qmd
    - note_granter.qmd
    - note_source.qmd
    - publisher.qmd
    - publication_interval.qmd
    - publication_place.qmd
    - publication_time.qmd
    - subject_topic.qmd
    - successor.qmd
    - title.qmd
    - title_uniform.qmd
    - uncontrolled.qmd

